DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS phone_contacts;
DROP TABLE IF EXISTS phone_contacts;

CREATE TABLE IF NOT EXISTS client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    name           VARCHAR(255)                            NOT NULL,
    surname        VARCHAR(255)                            NOT NULL,
    email_contacts json
);

CREATE TABLE IF NOT EXISTS phone_contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    phone_number text                                    NOT NULL
);

CREATE TABLE IF NOT EXISTS client_to_phone
(
    client_id BIGINT NOT NULL,
    phone_id  BIGINT NOT NULL
);

ALTER TABLE client_to_phone
    ADD CONSTRAINT client_to_phone_pk PRIMARY KEY (client_id, phone_id);