DROP TABLE IF EXISTS client;

CREATE TABLE IF NOT EXISTS client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    name           VARCHAR(255)                            NOT NULL,
    surname        VARCHAR(255)                            NOT NULL,
    phone_contacts json,
    email_contacts json,
);